services:
  app:
    image: node:20-alpine
    container_name: seniores_api
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - DB_PASS=secret
      - DATABASE_URL=mysql+pymysql://root:secret@db:3306/flaskdb
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: flask_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: flaskdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: